name: GitHub-Profile-3D-Contrib

on:
  schedule: # 01:00 JST == 16:00 UTC
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE }}
          USERNAME: ${{ github.rudgh46 }}
      - name: Commit & Push
        run: |
          git config user.name rudgh46
          git config user.email rudgh46@naver.com
          git add -A .
          git commit -m "generated"
          git push
